name: ZAP - API Scan
on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    name: Scan the api
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: main
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          format: ${{ secrets.ZAP_API_SCAN_FILE_FORMAT }}
          target: ${{ secrets.ZAP_API_SCAN_FILE }}
          cmd_options: ${{ secrets.ZAP_GLOBAL_CMD_OPTIONS }}
